sudo: required
dist: trusty
language: c
install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes autoconf automake libtool xutils-dev gcc make cmake libglib2.0-dev
env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
script:
  - set -e
  - mkdir /tmp/oio
  - export CMAKE_OPTS='-DCMAKE_INSTALL_PREFIX=/tmp/oio -DLD_LIBDIR=lib'
  - cmake ${CMAKE_OPTS} -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
  - make all
  - make install
